---
- name: Deploy to Tomcat
  hosts: localhost
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ lookup('env', 'WORKSPACE') }}/target/MavenAnsibleWebApp.war"
        dest: /opt/tomcat/webapps/MavenAnsibleWebApp.war
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat service
      systemd:
        name: tomcat
        state: restarted

